modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CustomNausea/issues"
displayURL="https://minecraft.curseforge.com/projects/custom-nausea"
logoFile="customnausea_icon.png"
authors="C4"
[[mods]]
modId="customnausea"
version="${file.jarVersion}"
displayName="Custom Nausea"
description='''
Allows modifying the strength of the Nausea screen effect, plus additional options.
'''
[[dependencies.comforts]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.comforts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.14)"
    ordering="NONE"
    side="BOTH"